### ISSUE TITLE
Console parser not working with some commands

### ISSUE THREAD

**Issue by LucioFranco** [CaptainCow95/Database#3] opened 2015-02-13 03:09 UTC

**Comment by CaptainCow95** [comment] 2015-02-16 00:48
This only seems to be happening on OS X, so I will need to determine if it is a mono on OS X issue or just a general mono issue.

**Comment by LucioFranco** [comment] 2015-02-16 01:04
Interesting it may be a bash problem. You could try running it on linux to see if it still isn't working

**Comment by CaptainCow95** [comment] 2015-02-16 02:21
I can't seem to reproduce this at all anymore. It don't get those errors at all on Linux using Bash, on OS X using Bash, or on OS X using the external console while debugging through Xamarin Studio.

**Comment by CaptainCow95** [comment] 2015-02-16 18:47
Closing for now since I can't reproduce it anymore.

**Closed as completed by CaptainCow95** 2015-02-16 18:47 UTC
Labels: bug
